language: cpp

branches:
  except:
  - gh-pages
  - feature/appveyor_pd

env:
  global:
  - GH_REPO_NAME: libossia
  - GH_REPO_REF: github.com/OSSIA/libossia.git

osx_image: xcode9
dist: trusty
sudo: required

# That was for RpiDocker build
# service:
# - docker

matrix:
  exclude:
  - os: linux
  - os: osx

  include:
  - os: linux
    env: BUILD_TYPE=Docs

  - os: linux
    env: BUILD_TYPE=Debug OSSIA_STATIC=0
    dist: trusty
  - os: linux
    env: BUILD_TYPE=Debug OSSIA_STATIC=1
    dist: trusty
  - os: linux
    env: BUILD_TYPE=Release OSSIA_STATIC=0
    dist: trusty
  - os: linux
    env: BUILD_TYPE=Release OSSIA_STATIC=1
    dist: trusty
  - os: linux
    env: BUILD_TYPE=PdRelease OSSIA_STATIC=1
    dist: trusty
#  - os: linux
#    env: BUILD_TYPE=RpiDocker OSSIA_STATIC=1
#    dist: trusty

  - os: linux
    env: BUILD_TYPE=RpiPdRelease OSSIA_STATIC=1
    dist: trusty

  - os: linux
    env: BUILD_TYPE=python
    dist: trusty
    python: 2.7

  - os: linux
    env: BUILD_TYPE=python
    dist: trusty
    python: 3.6

  - os: linux
    env: BUILD_TYPE=qml
    dist: trusty

  - os: osx
    env: BUILD_TYPE=python
    python: 2.7

  - os: osx
    env: BUILD_TYPE=qml

  - os: osx
    env: BUILD_TYPE=Debug OSSIA_STATIC=0
  - os: osx
    env: BUILD_TYPE=Debug OSSIA_STATIC=1
  - os: osx
    env: BUILD_TYPE=Release OSSIA_STATIC=0
  - os: osx
    env: BUILD_TYPE=Release OSSIA_STATIC=1
  - os: osx
    env: BUILD_TYPE=PdRelease OSSIA_STATIC=1
  - os: osx
    env: BUILD_TYPE=MaxRelease OSSIA_STATIC=1

  - os: linux
    env: BUILD_TYPE=Coverage

before_install:
- "./ci/deps.sh"

script:
- "./ci/build.sh"
deploy:
  - provider: releases
    api_key:
      secure: cuMgjuaFGGh7YxpIMP7dLyTzzRkAK6q1//5qZ1wHrnEjwtZK4+XRqQP4uQNCJsk22yrc9iu7AcJ9xsZ72xs3C4EXPLa7GlWLKrQD1M7J4viaZCb1AKiEjFYMEa6iRQf79ip7zDiWEQNV4aL+aJBZBLRZ4I8chvkKnUBaEOnVx6U=
    file:
      - ossia-pd-linux_x86_64.tar.gz
    skip_cleanup: true
    on:
      repo: OSSIA/libossia
      tags: true
      condition: $BUILD_TYPE = PdRelease && $TRAVIS_OS_NAME = linux
  - provider: releases
    api_key:
      secure: cuMgjuaFGGh7YxpIMP7dLyTzzRkAK6q1//5qZ1wHrnEjwtZK4+XRqQP4uQNCJsk22yrc9iu7AcJ9xsZ72xs3C4EXPLa7GlWLKrQD1M7J4viaZCb1AKiEjFYMEa6iRQf79ip7zDiWEQNV4aL+aJBZBLRZ4I8chvkKnUBaEOnVx6U=
    file:
      - ossia-pd-linux_arm.tar.gz
    skip_cleanup: true
    on:
      repo: OSSIA/libossia
      tags: true
      condition: $BUILD_TYPE = RpiPdRelease
  - provider: releases
    api_key:
      secure: cuMgjuaFGGh7YxpIMP7dLyTzzRkAK6q1//5qZ1wHrnEjwtZK4+XRqQP4uQNCJsk22yrc9iu7AcJ9xsZ72xs3C4EXPLa7GlWLKrQD1M7J4viaZCb1AKiEjFYMEa6iRQf79ip7zDiWEQNV4aL+aJBZBLRZ4I8chvkKnUBaEOnVx6U=
    file:
      - ossia-pd-osx.tar.gz
    skip_cleanup: true
    on:
      repo: OSSIA/libossia
      tags: true
      condition: $BUILD_TYPE = PdRelease && $TRAVIS_OS_NAME = osx
  - provider: releases
    api_key:
      secure: cuMgjuaFGGh7YxpIMP7dLyTzzRkAK6q1//5qZ1wHrnEjwtZK4+XRqQP4uQNCJsk22yrc9iu7AcJ9xsZ72xs3C4EXPLa7GlWLKrQD1M7J4viaZCb1AKiEjFYMEa6iRQf79ip7zDiWEQNV4aL+aJBZBLRZ4I8chvkKnUBaEOnVx6U=
    file:
      - ossia-max-osx.tar.gz
    skip_cleanup: true
    on:
      repo: OSSIA/libossia
      tags: true
      condition: $BUILD_TYPE = MaxRelease
    - provider: releases
    api_key:
      secure: cuMgjuaFGGh7YxpIMP7dLyTzzRkAK6q1//5qZ1wHrnEjwtZK4+XRqQP4uQNCJsk22yrc9iu7AcJ9xsZ72xs3C4EXPLa7GlWLKrQD1M7J4viaZCb1AKiEjFYMEa6iRQf79ip7zDiWEQNV4aL+aJBZBLRZ4I8chvkKnUBaEOnVx6U=
    file:
      - ossia-python-$TRAVIS_PYTHON_VERSION-linux_x86_64.tar.gz
    skip_cleanup: true
    on:
      repo: OSSIA/libossia
      tags: true
      condition: $BUILD_TYPE = python
