language: cpp

os:
  - osx
  - linux

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

osx_image: xcode7.2
dist: trusty
sudo: required


matrix:
  exclude:
    - os: linux
    - os: osx

  include:
  - os: linux
    env: BUILD_TYPE=Debug OSSIA_STATIC=0
  - os: linux
    env: BUILD_TYPE=Debug OSSIA_STATIC=1
  - os: linux
    env: BUILD_TYPE=Release OSSIA_STATIC=0
  - os: linux
    env: BUILD_TYPE=Release OSSIA_STATIC=1

  - os: osx
    env: BUILD_TYPE=Debug OSSIA_STATIC=0
  - os: osx
    env: BUILD_TYPE=Debug OSSIA_STATIC=1
  - os: osx
    env: BUILD_TYPE=Release OSSIA_STATIC=0
  - os: osx
    env: BUILD_TYPE=Release OSSIA_STATIC=1

  - os: linux
    env: BUILD_TYPE=Coverage

  - os: linux
    env: BUILD_TYPE=Docs

before_install:
- "./travis/deps.sh"

script:
- "./travis/build.sh"
