language: cpp

branches:
  except:
    - gh-pages

env:
  global:
    - GH_REPO_NAME: libossia
    - GH_REPO_REF: github.com/OSSIA/libossia.git

osx_image: xcode8.3
dist: trusty
sudo: required


matrix:
  exclude:
    - os: linux
    - os: osx

  include:
  - os: linux
    env: BUILD_TYPE=Docs

  - os: linux
    env: BUILD_TYPE=Debug OSSIA_STATIC=0
    dist: trusty
  - os: linux
    env: BUILD_TYPE=Debug OSSIA_STATIC=1
    dist: trusty
  - os: linux
    env: BUILD_TYPE=Release OSSIA_STATIC=0
    dist: trusty
  - os: linux
    env: BUILD_TYPE=Release OSSIA_STATIC=1
    dist: trusty

  - os: osx
    env: BUILD_TYPE=Debug OSSIA_STATIC=0
  - os: osx
    env: BUILD_TYPE=Debug OSSIA_STATIC=1
  - os: osx
    env: BUILD_TYPE=Release OSSIA_STATIC=0
  - os: osx
    env: BUILD_TYPE=Release OSSIA_STATIC=1

  - os: linux
    env: BUILD_TYPE=Coverage

before_install:
- "./travis/deps.sh"

script:
- "./travis/build.sh"
