image: Visual Studio 2017

environment:
  BOOST_ROOT: c:\Libraries\boost_1_64_0
  CTEST_OUTPUT_ON_FAILURE: 1

  matrix:
    - APPVEYOR_BUILD_TYPE: testing
      platform: x64
      configuration: Debug
      QTDIR: C:\Qt\5.9\msvc2017_64

    - APPVEYOR_BUILD_TYPE: testing
      platform: x64
      configuration: Release
      QTDIR: C:\Qt\5.9\msvc2017_64

    - APPVEYOR_BUILD_TYPE: Release
      platform: x64
      configuration: Release
      QTDIR: C:\Qt\5.9\msvc2017_64

    - APPVEYOR_BUILD_TYPE: Release
      configuration: Release
      QTDIR: C:\Qt\5.9\msvc2017_64

    - APPVEYOR_BUILD_TYPE: pd
      configuration: Release

    - APPVEYOR_BUILD_TYPE: max
      configuration: Release
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017 Win64
      CMAKE_GENERATOR_NAME_32BIT: Visual Studio 15 2017

    - APPVEYOR_BUILD_TYPE: python
      configuration: Release

    - APPVEYOR_BUILD_TYPE: qml
      configuration: Release
      QTDIR: C:\Qt\5.9\msvc2017_64

before_build:
  - git submodule update --init --recursive
  - ps: C:\projects\libossia\ci\before_build.ps1


build_script:
  - ps: C:\projects\libossia\ci\build.ps1
#build:
#  project: C:\projects\libossia\build\OSSIA.sln
#  parallel: true

after_build:
  - ps: C:\projects\libossia\ci\after_build.ps1

test_script:
  - ps: C:\projects\libossia\ci\test.ps1

artifacts:
  - path: ossia-pd-windows.zip
    name: ossia-pd-windows
    type: zip
  - path: ossia-max-windows.zip
    name: ossia-max-windows
    type: zip
  - path: ossia-qml-windows.zip
    name: ossia-qml-windonws
    type: zip
  - path: ossia-windows.zip
    name: ossia-windonws
    type: zip
  - path: ossia-python-windows.zip
    name: ossia-python-windows
    type: zip

deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: moePiJbJVxE0xx/iyPjZ4yAWJe+ZiJeVroktPbW6ybfamReA+oNojo3l23+/LtHt
  artifact: ossia-pd-windows.zip, ossia-max-windows.zip
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
