image: Visual Studio 2015

environment:
  BOOST_ROOT: c:\Libraries\boost_1_62_0

  matrix:
    - platform: Win32
      configuration: Debug
      QTDIR: C:\Qt\5.7\msvc2015
      CMAKE_GENERATOR_NAME: Visual Studio 14 2015
    - platform: Win32
      configuration: Release
      QTDIR: C:\Qt\5.7\msvc2015
      CMAKE_GENERATOR_NAME: Visual Studio 14 2015
    - platform: x64
      configuration: Debug
      QTDIR: C:\Qt\5.7\msvc2015_64
      CMAKE_GENERATOR_NAME: Visual Studio 14 2015 Win64
    - platform: x64
      configuration: Release
      QTDIR: C:\Qt\5.7\msvc2015_64
      CMAKE_GENERATOR_NAME: Visual Studio 14 2015 Win64

before_build:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - set PATH=%QTDIR%\bin;%PATH%
  - cmake -G "%CMAKE_GENERATOR_NAME%" -DOSSIA_PD=0 -DOSSIA_CI=1 -DOSSIA_TESTING=1 -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_PREFIX_PATH="%QTDIR%/lib/cmake/Qt5" ..

build:
  project: C:\projects\API\build\OSSIA.sln
  parallel: true

after_build:
  - copy OSSIA\%configuration%\ossia.dll Tests\%configuration%\

test_script:
  - cd C:\projects\API\build\
  - dir
  - cmake --build . --target RUN_TESTS --config %configuration%

