image: Visual Studio 2017

environment:
  BOOST_ROOT: c:/Libraries/boost_1_64_0
  CTEST_OUTPUT_ON_FAILURE: 1

  matrix:
    - platform: x64
      configuration: Debug
      QTDIR: C:\Qt\5.9\msvc2017_64
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017 Win64
      CMAKE_OPTION: -DOSSIA_PD=0 -DOSSIA_CI=1 -DOSSIA_TESTING=1 -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_PREFIX_PATH="%QTDIR%/lib/cmake/Qt5"
      APPVEYOR_BUILD_TYPE: testing
    - platform: x64
      configuration: Release
      QTDIR: C:\Qt\5.9\msvc2017_64
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017 Win64
      CMAKE_OPTION: -DOSSIA_PD=0 -DOSSIA_CI=1 -DOSSIA_TESTING=1 -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_PREFIX_PATH="%QTDIR%/lib/cmake/Qt5"
      APPVEYOR_BUILD_TYPE: testing
    - platform: x64
      configuration: Release
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017 Win64
      CMAKE_OPTION: -DOSSIA_PD=1 -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%" -DOSSIA_STATIC=1 -DOSSIA_QT=0 -DOSSIA_NO_QT=1 -DOSSIA_EXAMPLES=0 -DOSSIA_CI=1 -DOSSIA_TESTING=0 -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_PREFIX_PATH="%QTDIR%/lib/cmake/Qt5"
      APPVEYOR_BUILD_TYPE: pd

before_build:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - if exist "%QTDIR%\bin\" set PATH=%QTDIR%\bin;%PATH%
  - cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% %CMAKE_OPTION%  ..

build:
  project: C:\projects\libossia\build\OSSIA.sln
  parallel: true

after_build:
  - ps: C:\projects\libossia\travis\after_build.ps1

test_script:
  - ps: C:\projects\libossia\travis\test.ps1

artifacts:
  - path: ossia-pd-package
    name: ossia-pd-windows-x86_64
    type: zip
