environment:
  QTDIR: C:\Qt\5.7\msvc2015
  BOOST_ROOT: c:\Libraries\boost_1_60_0
  
configuration: Release

image: Visual Studio 2015
platform: x86

build_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - set PATH=%QTDIR%\bin;%PATH%
  - cmake -DOSSIA_TESTING=1 -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_PREFIX_PATH="%QTDIR%/lib/cmake/Qt5" ..
  - cmake --build . -- /p:Configuration=Debug /m
  - cmake --build . -- /p:Configuration=Release /m
  - cmake --build . --target ExperimentalTest

