image: Visual Studio 2017

environment:
  BOOST_ROOT: c:\Libraries\boost_1_64_0
  CTEST_OUTPUT_ON_FAILURE: 1

  matrix:
    - platform: x64
      configuration: Debug
      APPVEYOR_BUILD_TYPE: testing
      QTDIR: C:\Qt\5.9\msvc2017_64
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017 Win64
    - platform: x64
      configuration: Release
      APPVEYOR_BUILD_TYPE: testing
      QTDIR: C:\Qt\5.9\msvc2017_64
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017 Win64
    - configuration: Release
      APPVEYOR_BUILD_TYPE: pd
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017
    - configuration: Release
      APPVEYOR_BUILD_TYPE: max
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017 Win64
      CMAKE_GENERATOR_NAME_32BIT: Visual Studio 15 2017
    - configuration: Release
      APPVEYOR_BUILD_TYPE: python-32bit
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017
    - configuration: Release
      APPVEYOR_BUILD_TYPE: qml
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017 Win64

before_build:
  - git submodule update --init --recursive
  - ps: C:\projects\libossia\ci\before_build.ps1


build_script:
  - ps: C:\projects\libossia\ci\build.ps1
#build:
#  project: C:\projects\libossia\build\OSSIA.sln
#  parallel: true

after_build:
  - ps: C:\projects\libossia\ci\after_build.ps1

test_script:
  - ps: C:\projects\libossia\ci\test.ps1

artifacts:
  - path: install\ossia-pd-package
    name: ossia-pd-windows
    type: zip
  - path: install\ossia-max-package
    name: ossia-max-windows
    type: zip

deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: moePiJbJVxE0xx/iyPjZ4yAWJe+ZiJeVroktPbW6ybfamReA+oNojo3l23+/LtHt
  artifact: ossia-pd-windows.zip, ossia-max-windows.zip
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
