trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - '*'
pr:
  - '*'


variables:
  isGitTag: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]
  gitTag: $[replace(variables['Build.SourceBranch'], 'refs/tags/', '')]

stages:
  - stage: Build
    jobs:
      - job: MaxMacOS
        displayName: ossia-max (macOS)
        pool:
          vmImage: 'macos-10.15'

        steps:
        - checkout: self
          submodules: false

        - bash: |
            brew install ninja
          displayName: Dependencies

        - bash: |
            cd $(System.DefaultWorkingDirectory)
            mkdir build
            cd build
            cmake -GNinja $(Build.SourcesDirectory) -DOSSIA_MAX_ONLY=1 -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release
            cmake --build .
            cmake --build . --target install

            # Setup codesigning
            # Thanks https://www.update.rocks/blog/osx-signing-with-travis/
            (
              set +x
              KEY_CHAIN=build.keychain
              echo "$MAC_CERT_B64" | base64 --decode > ossia-cert.p12

              security create-keychain -p azure $KEY_CHAIN
              security default-keychain -s $KEY_CHAIN
              security unlock-keychain -p azure $KEY_CHAIN
              security import ossia-cert.p12 -k $KEY_CHAIN -P "$MAC_CERT_PASSWORD" -T /usr/bin/codesign;
              security set-key-partition-list -S apple-tool:,apple: -s -k azure $KEY_CHAIN

              rm -rf *.p12
            )

            security unlock-keychain -p azure build.keychain

            (
              cd install
              find ossia-max-package/ -name '*.dylib' -exec codesign --force --timestamp --sign "ossia.io" {} \;
              find ossia-max-package/ -name '*.mxo' -exec codesign --force --timestamp --sign "ossia.io" {} \;

              zip ossia-max.zip ossia-max-package/
              xcrun altool \
                   --notarize-app \
                   -t osx \
                   -f "ossia-max.zip" \
                   --primary-bundle-id "io.ossia.ossia-max" \
                   -u jeanmichael.celerier@gmail.com -p "@env:MAC_ALTOOL_PASSWORD"
              rm ossia-max.zip
            )

          displayName: Build
          env:
            MAC_CERT_B64: $(MAC_CERT_B64)
            MAC_CERT_PASSWORD: $(MAC_CERT_PASSWORD)
            MAC_ALTOOL_PASSWORD: $(MAC_ALTOOL_PASSWORD)

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/build/install/ossia-max-package
            artifactName: libossia-max-macos

      - job: MaxWin64
        displayName: ossia-max (Win64)
        pool:
          vmImage: 'windows-2019'

        steps:
        - checkout: self
          submodules: false

        - script: |
            cinst -y ninja

        - script: |
            pushd "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
            for /f "delims=" %%x in ('.\vswhere.exe -latest -property InstallationPath') do set VSPATH=%%x
            popd
            call "%VSPATH%\VC\Auxiliary\Build\vcvarsall.bat" x64

            cd $(System.DefaultWorkingDirectory)
            mkdir build
            cd build
            cmake -GNinja $(Build.SourcesDirectory) -DOSSIA_MAX_ONLY=1 -DCMAKE_SYSTEM_VERSION=7 -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release
            cmake --build .
            cmake --build . --target install
          displayName: Build

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/build/install/ossia-max-package
            artifactName: libossia-max-win64

  - stage: Assemble
    condition: succeeded()
    # see https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/GitHubReleaseV1

    jobs:
      - job: AssembleMax
        pool:
          vmImage: 'ubuntu-20.04'

        steps:
        - checkout: none
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: libossia-max-win64
            path: $(System.DefaultWorkingDirectory)
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: libossia-max-macos
            path: $(System.DefaultWorkingDirectory)

        - bash: |
            cd $(System.DefaultWorkingDirectory)
            zip -r ossia-max.zip ossia
          displayName: Package

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/ossia-max.zip
            artifactName: ossia-max

  - stage: GithubRelease
    jobs:
      - job: GithubRelease
        pool:
          vmImage: 'ubuntu-20.04'

        steps:
        - checkout: none
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: ossia-max
            path: $(System.ArtifactStagingDirectory)

        - bash: |
            if [ "$isGitTag" = "True" ]
            then
              RELEASE_NAME="$(gitTag)"
            else
              RELEASE_NAME="latest-ci-build"
            fi
            echo "##vso[task.setvariable variable=releaseName;]$RELEASE_NAME"
          displayName: Set Release Name

        - task: GitHubRelease@1
          inputs:
            gitHubConnection: github.com_jcelerier
            repositoryName: ossia/libossia
            action: 'edit'
            target: '$(Build.SourceVersion)'
            tagSource: userSpecifiedTag
            tag: '$(releaseName)'
            assetUploadMode: 'replace'
            isPreRelease: true
