name: Coverage

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/latest-ubuntu-toolchain
    - name: Install Dependencies
      run: |
        sudo gem install coveralls-lcov

        sudo apt-get install -yqq python3 python3-pip
        sudo pip3 install --upgrade wheel setuptools
        sudo pip3 install git+https://github.com/rpgillespie6/fastcov.git

        # For some reason gcov seems to be not available anymore...
        wget -nv https://github.com/ossia/sdk/releases/download/sdk14/gcov
        file ./gcov
        chmod +x ./gcov
        sudo cp ./gcov /usr/bin/gcov
        sudo cp ./gcov /usr/bin/gcov-9

        gcov-9 --version

    - name: Build
      run: |
        QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
        set +e
        source $QT_ENV_SCRIPT
        set -e
        
        cmake -B build -S ${GITHUB_WORKSPACE} \
          -DCMAKE_BUILD_TYPE=Debug \
          -DOSSIA_TESTING=1 \
          -DOSSIA_COVERAGE=1 \
          -DPORTAUDIO_ONLY_DYNAMIC=1 \
          -DOSSIA_PD=0 \
          -DOSSIA_QT=1 \
          -DOSSIA_C=1 
        cmake --build build -- -j2
        cmake --build build --target ossia_coverage || true
        rm -rf **/*.o

        find . -name '*.info'

        coveralls-lcov $(find . -name '*.info')