name: ossia-max-macos

on: push

# on:
#   push:
#     branches: [ $default-branch ]
#   pull_request:
#     branches: [ $default-branch ]

jobs:
  build:

    runs-on: [self-hosted, macOS]

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./tools/build-ossia-max.sh clean silent
    - name: Archive Max Package
      with:
        name: ossia-max-macos
        path: artifacts/ossia
