name: ossia-max

on: push

# on:
#   push:
#     branches: [ $default-branch ]
#   pull_request:
#     branches: [ $default-branch ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./tools/build-ossia-max.sh clean silent
    - name: Archive Max Package
      uses: actions/upload-artifact@v2
      with:
        name: ossia-max-macos
        path: artifacts/ossia

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure environment
      run: ./ci/before_build.ps1
    - name: Build
      run: ./ci/build.ps1
    - name: Package
      run: ./ci/after_build.ps1
    - name: Archive Max Package
      uses: actions/upload-artifact@v2
      with:
        name: ossia-max-windows
        path: artifacts/ossia