name: ossia-max

on: push

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./tools/build-ossia-max.sh clean silent
    - name: Archive Max Package
      uses: actions/upload-artifact@v2
      with:
        name: ossia-max-macos
        path: artifacts/ossia
    - name: Upload logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: "*.log"

  build-windows:
    runs-on: windows-latest
    env:
      APPVEYOR_BUILD_TYPE: max
      configuration: Release
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: cinst -y ninja
    - name : build
      shell: cmd
      run: |
        for /f "delims=" %%x in ('vswhere.exe -latest -property InstallationPath') do set VSPATH=%%x
        call "%VSPATH%\VC\Auxiliary\Build\vcvarsall.bat" x64

        echo Workspace: %GITHUB_WORKSPACE%
        cd %GITHUB_WORKSPACE%
        mkdir build
        cd build
        cmake -GNinja %GITHUB_WORKSPACE% -DOSSIA_MAX_ONLY=1 -DCMAKE_SYSTEM_VERSION=7 -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release
        cmake --build .
        cmake --build . --target install
    - name: Archive Max Package
      uses: actions/upload-artifact@v2
      with:
        name: ossia-max-windows
        path: build/install/ossia-max-package/ossia
    - name: Upload logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: "*.log"